version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: epicpartners
      MYSQL_PASSWORD: 09po:L?>
      MYSQL_ROOT_PASSWORD: 09po:L?>
      restart: always
    networks:
      - epic-localhost
  back:
    image: newaldan/epic-partners-back
    container_name: back
    depends_on:
      - db
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
    networks:
      - epic-localhost
networks:
  epic-localhost:
    driver: bridge
volumes:
  db-data: